version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_snowflake
    restart: always
    environment:
      POSTGRES_USER:  dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB:     mockdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

volumes:
  pg_data:
